services:
  cuneiform:
    build: .
    ports:
      - "8200:8200"
    environment:
      - BAO_DEV_ROOT_TOKEN_ID=root
      - BAO_ADDR=http://0.0.0.0:8200
      - BAO_API_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-listen-address="0.0.0.0:8200"
    volumes:
      - cuneiform-data:/openbao/data

volumes:
  cuneiform-data:
